import FullProfilePage from "@/components/profiles/FullProfilePage";

export default function TestFullProfile() {
  const sampleProfile = {
    id: "1",
    lookingFor: "bride" as const,
    name: "Ayesha Rahman",
    age: 26,
    dateOfBirth: "15 March 1998",
    height: "5'4\"",
    weight: "55 kg",
    bodyType: "Average",
    complexion: "Fair",
    bloodGroup: "B+",
    currentlyLivesIn: "Dhaka",
    dhakaArea: "Gulshan",
    familyHomeDistrict: "Chittagong",
    willingToRelocate: "Yes, after marriage",
    education: "MBA in Finance",
    institutionName: "Dhaka University",
    workSector: "Banking",
    profession: "Senior Bank Officer",
    monthlyIncome: 45000,
    workAfterMarriage: "Will continue",
    religion: "Islam - Sunni",
    religiousPractice: "Religious",
    namaz: "5 times daily",
    quranReading: "Can read fluently",
    hijab: "Yes",
    maritalStatus: "Never married",
    profileManagedBy: "Parents",
    candidateApproved: true,
    familyType: "Nuclear family",
    familyValues: "Moderate",
    fatherProfession: "Government officer",
    motherProfession: "Homemaker",
    siblings: "1 brother, 1 sister",
    homeStatus: "Own house",
    livingArrangement: "Separate after marriage",
    motherTongue: "Bangla",
    englishSpeaking: "Fluent",
    diet: "Non-vegetarian",
    smoking: "No",
    drinking: "No",
    whenToMarry: "Within 6 months",
    howToCommunicate: "Through guardian",
    isVerified: true,
    isPremium: true,
    lastActive: "Active 2 hours ago",
    aboutMe: "I am a practicing Muslim, family-oriented person looking for a life partner who shares similar values. I believe in maintaining a balance between career and family life.",
    lookingForInPartner: "Looking for a practicing Muslim from a good family background. Should be well-educated, respectful towards elders, and willing to support mutual career growth."
  };

  return <FullProfilePage profile={sampleProfile} />;
}